version: "3"
services:
  #PHP service
  app_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: php_app
    container_name: app_backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_backend
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network-backend

  #Nginx service
  web_server-backend:
    image: nginx:alpine
    container_name: web_server-backend
    restart: unless-stopped
    tty: true
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network-backend

  #Mysql service
  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: backend_api
      MYSQL_USER: backend_api
      MYSQL_PASSWORD: backend_api
      MYSQL_ROOT_PASSWORD: backend_api
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
#    volumes:
#      - ./data-mysql:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network-backend

  #Phpmyadmin
  phpmyadmin_backend:
    container_name: phpmyadmin_backend
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8889:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: backend_api
    networks:
      - app-network-backend
  #Redis
  redis_backend:
    image: redis:6.2-alpine
    container_name: redis_backend
    restart: always
    depends_on:
      - database
      - app_backend
      - web_server-backend
    tty: true
    ports:
      - "6377:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass lightup_lp
    volumes:
      - ./cache-redis:/data
    networks:
      - app-network-backend

#Networks
networks:
  app-network-backend:
    name: app-network-backend
    driver: bridge
#Volumes
volumes:
  dbdata:
    name: dbdata
    driver: local
